py_binary(
    name='flatten_image',
    srcs=['flatten_image.py'],
    visibility=['//visibility:public'],
)


py_binary(
    name='deb_deps',
    srcs=['deb_deps.py'],
    visibility=['//visibility:public'],
)


py_binary(
    name='copy_files',
    srcs=['copy_files.py'],
    visibility=['//visibility:public'],
)


py_binary(
    name='build_tar',
    srcs=['build_tar.py'],
    visibility=['//visibility:public'],
)


sh_binary(
    name='pip_hack',
    srcs=['pip_hack.sh'],
    visibility=['//visibility:public'],
)


exports_files(['py_run.tmpl'])
